services:
  - type: web
    name: codereddy
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./out
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
